#!/bin/sh

[ -f "/etc/multiwan-nft.user" ] && {
	. /lib/functions.sh
	. /lib/multiwan-nft/multiwan_nft.sh
	initscript=/etc/init.d/multiwan-nft
	. /lib/functions/procd.sh

	[ "$MULTIWAN_NFT_SHUTDOWN" != 1 ] && procd_lock

	[ "$MULTIWAN_NFT_SHUTDOWN" != 1 ] && ! /etc/init.d/multiwan-nft running && {
		exit 0
	}

	config_load 'multiwan-nft'

	config_get_bool enabled "$INTERFACE" enabled 0
	[ "${enabled}" -eq 1 ] || {
		exit 0
	}

	[ -x /etc/multiwan-nft.user ] || chmod 755 /etc/multiwan-nft.user
	env -i ACTION="$ACTION" INTERFACE="$INTERFACE" DEVICE="$DEVICE" /etc/multiwan-nft.user 1000>&-
}

exit 0
